name: 'AzureBicepDeploy'
 
on:
  push:
    branches:
    - main
  pull_request:
 
jobs:
 
  build-and-deploy:
      runs-on: ubuntu-latest
      steps:

        # Checkout code
      - uses: actions/checkout@main

        # Log into Azure
      - uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

        # Deploy Bicep file, need to point parameters to the main.parameters.json location
      - name: deploy
        uses: azure/arm-deploy@v1
        with:
          subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION }}
          template: ./deployment/bicep/main.bicep
          parameters: ./deployment/bicep/main.parameters.json